/* The canonical registry of programs this Suite knows about.

   One list, and only one. A program appears here whether or not the Suite can
   render it yet; what makes it selectable is that it names a `config`, and the
   config file existing is what makes that true. There is deliberately no
   second "available teams" list to drift out of step - availability is derived
   (docs/decisions/0014-one-registry.md).

     teams/index.js  ->  TEAM_REGISTRY  ->  TeamOS.registry  ->  the chooser
                                                              ->  the boot script
                                                              ->  the worker

   Fields:

     id          the Suite's own id for the program. Lower case, digits and
                 hyphens only - it becomes a file name and a ?team= value, and
                 the boot script refuses anything else.
     name        how the program is written out.
     short       how it is written where space is tight.
     conference  for grouping in the chooser. A program with none says
                 "Independent".
     abbr, nick  the provider's short code and nickname, which people search
                 by. The nickname is also shown under the program's name.
     providerId  the data provider's id for the program, so TeamOS can ask
                 for its mark (logo). Optional.
     config      teams/<id>.js, when one exists. ABSENT means the program is
                 known but not yet selectable, which is a real state: it is
                 what the chooser greys out rather than hiding.

   GENERATED by tools/build-registry.js from ESPN's standings page, weekly,
   by the Action. Do not hand-edit the roster or the conferences: the next run
   overwrites them. `name` IS preserved across runs, for the case where the
   product calls a program something the provider does not. `providerId` is
   also filled in by tools/registry-ids.js from ESPN's weekly scoreboards, so
   marks do not depend on the standings page being reachable.

   Making a program selectable is writing teams/<id>.js. The generator reads
   the filesystem and fills `config` in for you; nothing declares availability.

   The roster is a UNION across runs, so a bad parse can never remove a
   program, and the generator refuses to shrink it or to emit a list too short
   to be FBS. tools/registrycheck.js keeps it honest either way. */

var TEAM_REGISTRY = [

  { id: "air-force", name: "Air Force", short: "Air Force", conference: "Mountain West Conference", abbr: "AFA", nick: "Falcons", providerId: "2005" },
  { id: "akron", name: "Akron", short: "Akron", conference: "Mid-American Conference", abbr: "AKR", nick: "Zips", providerId: "2006" },
  { id: "alabama", name: "Alabama", short: "Alabama", conference: "Southeastern Conference", abbr: "ALA", nick: "Crimson Tide", providerId: "333" },
  { id: "app-state", name: "App State", short: "App State", conference: "Sun Belt Conference", abbr: "APP", nick: "Mountaineers", providerId: "2026" },
  { id: "arizona", name: "Arizona", short: "Arizona", conference: "Big 12 Conference", abbr: "ARIZ", nick: "Wildcats", providerId: "12" },
  { id: "arizona-state", name: "Arizona State", short: "Arizona State", conference: "Big 12 Conference", abbr: "ASU", nick: "Sun Devils", providerId: "9" },
  { id: "arkansas", name: "Arkansas", short: "Arkansas", conference: "Southeastern Conference", abbr: "ARK", nick: "Razorbacks", providerId: "8" },
  { id: "arkansas-state", name: "Arkansas State", short: "Arkansas State", conference: "Sun Belt Conference", abbr: "ARST", nick: "Red Wolves", providerId: "2032" },
  { id: "army", name: "Army", short: "Army", conference: "American Conference", abbr: "ARMY", nick: "Black Knights", providerId: "349" },
  { id: "auburn", name: "Auburn", short: "Auburn", conference: "Southeastern Conference", abbr: "AUB", nick: "Tigers", providerId: "2" },
  { id: "ball-state", name: "Ball State", short: "Ball State", conference: "Mid-American Conference", abbr: "BALL", nick: "Cardinals", providerId: "2050" },
  { id: "baylor", name: "Baylor", short: "Baylor", conference: "Big 12 Conference", abbr: "BAY", nick: "Bears", providerId: "239" },
  { id: "boise-state", name: "Boise State", short: "Boise State", conference: "Pac-12 Conference", abbr: "BOIS", nick: "Broncos", providerId: "68" },
  { id: "boston-college", name: "Boston College", short: "Boston College", conference: "Atlantic Coast Conference", abbr: "BC", nick: "Eagles", providerId: "103" },
  { id: "bowling-green", name: "Bowling Green", short: "Bowling Green", conference: "Mid-American Conference", abbr: "BGSU", nick: "Falcons", providerId: "189" },
  { id: "buffalo", name: "Buffalo", short: "Buffalo", conference: "Mid-American Conference", abbr: "BUFF", nick: "Bulls", providerId: "2084" },
  { id: "byu", name: "BYU", short: "BYU", conference: "Big 12 Conference", abbr: "BYU", nick: "Cougars", providerId: "252" },
  { id: "california", name: "California", short: "California", conference: "Atlantic Coast Conference", abbr: "CAL", nick: "Golden Bears", providerId: "25" },
  { id: "central-michigan", name: "Central Michigan", short: "Central Michigan", conference: "Mid-American Conference", abbr: "CMU", nick: "Chippewas", providerId: "2117" },
  { id: "charlotte", name: "Charlotte", short: "Charlotte", conference: "American Conference", abbr: "CLT", nick: "49ers", providerId: "2429" },
  { id: "cincinnati", name: "Cincinnati", short: "Cincinnati", conference: "Big 12 Conference", abbr: "CIN", nick: "Bearcats", providerId: "2132" },
  { id: "clemson", name: "Clemson", short: "Clemson", conference: "Atlantic Coast Conference", abbr: "CLEM", nick: "Tigers", providerId: "228" },
  { id: "coastal-carolina", name: "Coastal Carolina", short: "Coastal Carolina", conference: "Sun Belt Conference", abbr: "CCU", nick: "Chanticleers", providerId: "324" },
  { id: "colorado", name: "Colorado", short: "Colorado", conference: "Big 12 Conference", abbr: "COLO", nick: "Buffaloes", providerId: "38" },
  { id: "colorado-state", name: "Colorado State", short: "Colorado State", conference: "Pac-12 Conference", abbr: "CSU", nick: "Rams", providerId: "36" },
  { id: "delaware", name: "Delaware", short: "Delaware", conference: "Conference USA", abbr: "DEL", nick: "Blue Hens", providerId: "48" },
  { id: "duke", name: "Duke", short: "Duke", conference: "Atlantic Coast Conference", abbr: "DUKE", nick: "Blue Devils", providerId: "150" },
  { id: "east-carolina", name: "East Carolina", short: "East Carolina", conference: "American Conference", abbr: "ECU", nick: "Pirates", providerId: "151" },
  { id: "eastern-michigan", name: "Eastern Michigan", short: "Eastern Michigan", conference: "Mid-American Conference", abbr: "EMU", nick: "Eagles", providerId: "2199" },
  { id: "florida", name: "Florida", short: "Florida", conference: "Southeastern Conference", abbr: "FLA", nick: "Gators", providerId: "57" },
  { id: "florida-atlantic", name: "Florida Atlantic", short: "Florida Atlantic", conference: "American Conference", abbr: "FAU", nick: "Owls", providerId: "2226" },
  { id: "florida-international", name: "Florida International", short: "Florida International", conference: "Conference USA", abbr: "FIU", nick: "Panthers", providerId: "2229" },
  { id: "florida-state", name: "Florida State", short: "Florida State", conference: "Atlantic Coast Conference", abbr: "FSU", nick: "Seminoles", providerId: "52" },
  { id: "fresno-state", name: "Fresno State", short: "Fresno State", conference: "Pac-12 Conference", abbr: "FRES", nick: "Bulldogs", providerId: "278" },
  { id: "georgia", name: "Georgia", short: "Georgia", conference: "Southeastern Conference", abbr: "UGA", nick: "Bulldogs", providerId: "61" },
  { id: "georgia-southern", name: "Georgia Southern", short: "Georgia Southern", conference: "Sun Belt Conference", abbr: "GASO", nick: "Eagles", providerId: "290" },
  { id: "georgia-state", name: "Georgia State", short: "Georgia State", conference: "Sun Belt Conference", abbr: "GAST", nick: "Panthers", providerId: "2247" },
  { id: "georgia-tech", name: "Georgia Tech", short: "Georgia Tech", conference: "Atlantic Coast Conference", abbr: "GT", nick: "Yellow Jackets", providerId: "59" },
  { id: "hawaii", name: "Hawai'i", short: "Hawai'i", conference: "Mountain West Conference", abbr: "HAW", nick: "Rainbow Warriors", providerId: "62" },
  { id: "houston", name: "Houston", short: "Houston", conference: "Big 12 Conference", abbr: "HOU", nick: "Cougars", providerId: "248" },
  { id: "illinois", name: "Illinois", short: "Illinois", conference: "Big Ten Conference", abbr: "ILL", nick: "Fighting Illini", providerId: "356" },
  { id: "indiana", name: "Indiana", short: "Indiana", conference: "Big Ten Conference", abbr: "IU", nick: "Hoosiers", providerId: "84" },
  { id: "iowa", name: "Iowa", short: "Iowa", conference: "Big Ten Conference", abbr: "IOWA", nick: "Hawkeyes", providerId: "2294" },
  { id: "iowa-state", name: "Iowa State", short: "Iowa State", conference: "Big 12 Conference", abbr: "ISU", nick: "Cyclones", providerId: "66" },
  { id: "jacksonville-state", name: "Jacksonville State", short: "Jacksonville State", conference: "Conference USA", abbr: "JXST", nick: "Gamecocks", providerId: "55" },
  { id: "james-madison", name: "James Madison", short: "James Madison", conference: "Sun Belt Conference", abbr: "JMU", nick: "Dukes", providerId: "256" },
  { id: "kansas", name: "Kansas", short: "Kansas", conference: "Big 12 Conference", abbr: "KU", nick: "Jayhawks", providerId: "2305" },
  { id: "kansas-state", name: "Kansas State", short: "Kansas State", conference: "Big 12 Conference", abbr: "KSU", nick: "Wildcats", providerId: "2306" },
  { id: "kennesaw-state", name: "Kennesaw State", short: "Kennesaw State", conference: "Conference USA", abbr: "KENN", nick: "Owls", providerId: "338" },
  { id: "kent-state", name: "Kent State", short: "Kent State", conference: "Mid-American Conference", abbr: "KENT", nick: "Golden Flashes", providerId: "2309" },
  { id: "kentucky", name: "Kentucky", short: "Kentucky", conference: "Southeastern Conference", abbr: "UK", nick: "Wildcats", providerId: "96" },
  { id: "liberty", name: "Liberty", short: "Liberty", conference: "Conference USA", abbr: "LIB", nick: "Flames", providerId: "2335" },
  { id: "louisiana", name: "Louisiana", short: "Louisiana", conference: "Sun Belt Conference", abbr: "UL", nick: "Ragin' Cajuns", providerId: "309" },
  { id: "louisiana-tech", name: "Louisiana Tech", short: "Louisiana Tech", conference: "Sun Belt Conference", abbr: "LT", nick: "Bulldogs", providerId: "2348" },
  { id: "louisville", name: "Louisville", short: "Louisville", conference: "Atlantic Coast Conference", abbr: "LOU", nick: "Cardinals", providerId: "97" },
  { id: "lsu", name: "LSU", short: "LSU", conference: "Southeastern Conference", abbr: "LSU", nick: "Tigers", providerId: "99" },
  { id: "marshall", name: "Marshall", short: "Marshall", conference: "Sun Belt Conference", abbr: "MRSH", nick: "Thundering Herd", providerId: "276" },
  { id: "maryland", name: "Maryland", short: "Maryland", conference: "Big Ten Conference", abbr: "MD", nick: "Terrapins", providerId: "120" },
  { id: "massachusetts", name: "Massachusetts", short: "Massachusetts", conference: "Mid-American Conference", abbr: "MASS", nick: "Minutemen", providerId: "113" },
  { id: "memphis", name: "Memphis", short: "Memphis", conference: "American Conference", abbr: "MEM", nick: "Tigers", providerId: "235" },
  { id: "miami", name: "Miami", short: "Miami", conference: "Atlantic Coast Conference", abbr: "MIA", nick: "Hurricanes", providerId: "2390" },
  { id: "miami-oh", name: "Miami (OH)", short: "Miami (OH)", conference: "Mid-American Conference", abbr: "M-OH", nick: "RedHawks", providerId: "193" },
  { id: "michigan", name: "Michigan", short: "Michigan", conference: "Big Ten Conference", abbr: "MICH", nick: "Wolverines", providerId: "130" },
  { id: "michigan-state", name: "Michigan State", short: "Michigan State", conference: "Big Ten Conference", abbr: "MSU", nick: "Spartans", providerId: "127" },
  { id: "middle-tennessee", name: "Middle Tennessee", short: "Middle Tennessee", conference: "Conference USA", abbr: "MTSU", nick: "Blue Raiders", providerId: "2393" },
  { id: "minnesota", name: "Minnesota", short: "Minnesota", conference: "Big Ten Conference", abbr: "MINN", nick: "Golden Gophers", providerId: "135" },
  { id: "mississippi-state", name: "Mississippi State", short: "Mississippi State", conference: "Southeastern Conference", abbr: "MSST", nick: "Bulldogs", providerId: "344" },
  { id: "missouri", name: "Missouri", short: "Missouri", conference: "Southeastern Conference", abbr: "MIZ", nick: "Tigers", providerId: "142" },
  { id: "missouri-state", name: "Missouri State", short: "Missouri State", conference: "Conference USA", abbr: "MOST", nick: "Bears", providerId: "2623" },
  { id: "navy", name: "Navy", short: "Navy", conference: "American Conference", abbr: "NAVY", nick: "Midshipmen", providerId: "2426" },
  { id: "nc-state", name: "NC State", short: "NC State", conference: "Atlantic Coast Conference", abbr: "NCSU", nick: "Wolfpack", providerId: "152" },
  { id: "nebraska", name: "Nebraska", short: "Nebraska", conference: "Big Ten Conference", abbr: "NEB", nick: "Cornhuskers", providerId: "158" },
  { id: "nevada", name: "Nevada", short: "Nevada", conference: "Mountain West Conference", abbr: "NEV", nick: "Wolf Pack", providerId: "2440" },
  { id: "new-mexico", name: "New Mexico", short: "New Mexico", conference: "Mountain West Conference", abbr: "UNM", nick: "Lobos", providerId: "167" },
  { id: "new-mexico-state", name: "New Mexico State", short: "New Mexico State", conference: "Conference USA", abbr: "NMSU", nick: "Aggies", providerId: "166" },
  { id: "north-carolina", name: "North Carolina", short: "North Carolina", conference: "Atlantic Coast Conference", abbr: "UNC", nick: "Tar Heels", providerId: "153" },
  { id: "north-dakota-state", name: "North Dakota State", short: "North Dakota State", conference: "Mountain West Conference", abbr: "NDSU", nick: "Bison", providerId: "2449" },
  { id: "north-texas", name: "North Texas", short: "North Texas", conference: "American Conference", abbr: "UNT", nick: "Mean Green", providerId: "249" },
  { id: "northern-illinois", name: "Northern Illinois", short: "Northern Illinois", conference: "Mountain West Conference", abbr: "NIU", nick: "Huskies", providerId: "2459" },
  { id: "northwestern", name: "Northwestern", short: "Northwestern", conference: "Big Ten Conference", abbr: "NU", nick: "Wildcats", providerId: "77" },
  { id: "notre-dame", name: "Notre Dame", short: "Notre Dame", conference: "FBS Independents", abbr: "ND", nick: "Fighting Irish", providerId: "87", config: "teams/notre-dame.js" },
  { id: "ohio", name: "Ohio", short: "Ohio", conference: "Mid-American Conference", abbr: "OHIO", nick: "Bobcats", providerId: "195" },
  { id: "ohio-state", name: "Ohio State", short: "Ohio State", conference: "Big Ten Conference", abbr: "OSU", nick: "Buckeyes", providerId: "194", config: "teams/ohio-state.js" },
  { id: "oklahoma", name: "Oklahoma", short: "Oklahoma", conference: "Southeastern Conference", abbr: "OU", nick: "Sooners", providerId: "201" },
  { id: "oklahoma-state", name: "Oklahoma State", short: "Oklahoma State", conference: "Big 12 Conference", abbr: "OKST", nick: "Cowboys", providerId: "197" },
  { id: "old-dominion", name: "Old Dominion", short: "Old Dominion", conference: "Sun Belt Conference", abbr: "ODU", nick: "Monarchs", providerId: "295" },
  { id: "ole-miss", name: "Ole Miss", short: "Ole Miss", conference: "Southeastern Conference", abbr: "MISS", nick: "Rebels", providerId: "145" },
  { id: "oregon", name: "Oregon", short: "Oregon", conference: "Big Ten Conference", abbr: "ORE", nick: "Ducks", providerId: "2483" },
  { id: "oregon-state", name: "Oregon State", short: "Oregon State", conference: "Pac-12 Conference", abbr: "ORST", nick: "Beavers", providerId: "204" },
  { id: "penn-state", name: "Penn State", short: "Penn State", conference: "Big Ten Conference", abbr: "PSU", nick: "Nittany Lions", providerId: "213" },
  { id: "pittsburgh", name: "Pittsburgh", short: "Pittsburgh", conference: "Atlantic Coast Conference", abbr: "PITT", nick: "Panthers", providerId: "221" },
  { id: "purdue", name: "Purdue", short: "Purdue", conference: "Big Ten Conference", abbr: "PUR", nick: "Boilermakers", providerId: "2509" },
  { id: "rice", name: "Rice", short: "Rice", conference: "American Conference", abbr: "RICE", nick: "Owls", providerId: "242" },
  { id: "rutgers", name: "Rutgers", short: "Rutgers", conference: "Big Ten Conference", abbr: "RUTG", nick: "Scarlet Knights", providerId: "164" },
  { id: "sacramento-state", name: "Sacramento State", short: "Sacramento State", conference: "Mid-American Conference", abbr: "SAC", nick: "Hornets", providerId: "16" },
  { id: "sam-houston", name: "Sam Houston", short: "Sam Houston", conference: "Conference USA", abbr: "SHSU", nick: "Bearkats", providerId: "2534" },
  { id: "san-diego-state", name: "San Diego State", short: "San Diego State", conference: "Pac-12 Conference", abbr: "SDSU", nick: "Aztecs", providerId: "21" },
  { id: "san-jose-state", name: "San José State", short: "San José State", conference: "Mountain West Conference", abbr: "SJSU", nick: "Spartans", providerId: "23" },
  { id: "smu", name: "SMU", short: "SMU", conference: "Atlantic Coast Conference", abbr: "SMU", nick: "Mustangs", providerId: "2567" },
  { id: "south-alabama", name: "South Alabama", short: "South Alabama", conference: "Sun Belt Conference", abbr: "USA", nick: "Jaguars", providerId: "6" },
  { id: "south-carolina", name: "South Carolina", short: "South Carolina", conference: "Southeastern Conference", abbr: "SC", nick: "Gamecocks", providerId: "2579" },
  { id: "south-florida", name: "South Florida", short: "South Florida", conference: "American Conference", abbr: "USF", nick: "Bulls", providerId: "58" },
  { id: "southern-miss", name: "Southern Miss", short: "Southern Miss", conference: "Sun Belt Conference", abbr: "USM", nick: "Golden Eagles", providerId: "2572" },
  { id: "stanford", name: "Stanford", short: "Stanford", conference: "Atlantic Coast Conference", abbr: "STAN", nick: "Cardinal", providerId: "24" },
  { id: "syracuse", name: "Syracuse", short: "Syracuse", conference: "Atlantic Coast Conference", abbr: "SYR", nick: "Orange", providerId: "183" },
  { id: "tcu", name: "TCU", short: "TCU", conference: "Big 12 Conference", abbr: "TCU", nick: "Horned Frogs", providerId: "2628" },
  { id: "temple", name: "Temple", short: "Temple", conference: "American Conference", abbr: "TEM", nick: "Owls", providerId: "218" },
  { id: "tennessee", name: "Tennessee", short: "Tennessee", conference: "Southeastern Conference", abbr: "TENN", nick: "Volunteers", providerId: "2633" },
  { id: "texas", name: "Texas", short: "Texas", conference: "Southeastern Conference", abbr: "TEX", nick: "Longhorns", providerId: "251" },
  { id: "texas-am", name: "Texas A&M", short: "Texas A&M", conference: "Southeastern Conference", abbr: "TA&M", nick: "Aggies", providerId: "245" },
  { id: "texas-state", name: "Texas State", short: "Texas State", conference: "Pac-12 Conference", abbr: "TXST", nick: "Bobcats", providerId: "326" },
  { id: "texas-tech", name: "Texas Tech", short: "Texas Tech", conference: "Big 12 Conference", abbr: "TTU", nick: "Red Raiders", providerId: "2641" },
  { id: "toledo", name: "Toledo", short: "Toledo", conference: "Mid-American Conference", abbr: "TOL", nick: "Rockets", providerId: "2649" },
  { id: "troy", name: "Troy", short: "Troy", conference: "Sun Belt Conference", abbr: "TROY", nick: "Trojans", providerId: "2653" },
  { id: "tulane", name: "Tulane", short: "Tulane", conference: "American Conference", abbr: "TULN", nick: "Green Wave", providerId: "2655" },
  { id: "tulsa", name: "Tulsa", short: "Tulsa", conference: "American Conference", abbr: "TLSA", nick: "Golden Hurricane", providerId: "202" },
  { id: "uab", name: "UAB", short: "UAB", conference: "American Conference", abbr: "UAB", nick: "Blazers", providerId: "5" },
  { id: "ucf", name: "UCF", short: "UCF", conference: "Big 12 Conference", abbr: "UCF", nick: "Knights", providerId: "2116" },
  { id: "ucla", name: "UCLA", short: "UCLA", conference: "Big Ten Conference", abbr: "UCLA", nick: "Bruins", providerId: "26" },
  { id: "uconn", name: "UConn", short: "UConn", conference: "FBS Independents", abbr: "CONN", nick: "Huskies", providerId: "41" },
  { id: "ul-monroe", name: "UL Monroe", short: "UL Monroe", conference: "Sun Belt Conference", abbr: "ULM", nick: "Warhawks", providerId: "2433" },
  { id: "unlv", name: "UNLV", short: "UNLV", conference: "Mountain West Conference", abbr: "UNLV", nick: "Rebels", providerId: "2439" },
  { id: "usc", name: "USC", short: "USC", conference: "Big Ten Conference", abbr: "USC", nick: "Trojans", providerId: "30" },
  { id: "utah", name: "Utah", short: "Utah", conference: "Big 12 Conference", abbr: "UTAH", nick: "Utes", providerId: "254" },
  { id: "utah-state", name: "Utah State", short: "Utah State", conference: "Pac-12 Conference", abbr: "USU", nick: "Aggies", providerId: "328" },
  { id: "utep", name: "UTEP", short: "UTEP", conference: "Mountain West Conference", abbr: "UTEP", nick: "Miners", providerId: "2638" },
  { id: "utsa", name: "UTSA", short: "UTSA", conference: "American Conference", abbr: "UTSA", nick: "Roadrunners", providerId: "2636" },
  { id: "vanderbilt", name: "Vanderbilt", short: "Vanderbilt", conference: "Southeastern Conference", abbr: "VAN", nick: "Commodores", providerId: "238" },
  { id: "virginia", name: "Virginia", short: "Virginia", conference: "Atlantic Coast Conference", abbr: "UVA", nick: "Cavaliers", providerId: "258" },
  { id: "virginia-tech", name: "Virginia Tech", short: "Virginia Tech", conference: "Atlantic Coast Conference", abbr: "VT", nick: "Hokies", providerId: "259" },
  { id: "wake-forest", name: "Wake Forest", short: "Wake Forest", conference: "Atlantic Coast Conference", abbr: "WAKE", nick: "Demon Deacons", providerId: "154" },
  { id: "washington", name: "Washington", short: "Washington", conference: "Big Ten Conference", abbr: "WASH", nick: "Huskies", providerId: "264" },
  { id: "washington-state", name: "Washington State", short: "Washington State", conference: "Pac-12 Conference", abbr: "WSU", nick: "Cougars", providerId: "265" },
  { id: "west-virginia", name: "West Virginia", short: "West Virginia", conference: "Big 12 Conference", abbr: "WVU", nick: "Mountaineers", providerId: "277" },
  { id: "western-kentucky", name: "Western Kentucky", short: "Western Kentucky", conference: "Conference USA", abbr: "WKU", nick: "Hilltoppers", providerId: "98" },
  { id: "western-michigan", name: "Western Michigan", short: "Western Michigan", conference: "Mid-American Conference", abbr: "WMU", nick: "Broncos", providerId: "2711" },
  { id: "wisconsin", name: "Wisconsin", short: "Wisconsin", conference: "Big Ten Conference", abbr: "WIS", nick: "Badgers", providerId: "275" },
  { id: "wyoming", name: "Wyoming", short: "Wyoming", conference: "Mountain West Conference", abbr: "WYO", nick: "Cowboys", providerId: "2751" }

];
