/* The canonical registry of programs this Suite knows about.

   One list, and only one. A program appears here whether or not the Suite can
   render it yet; what makes it selectable is that it names a `config`, and the
   config file existing is what makes that true. There is deliberately no
   second "available teams" list to drift out of step - availability is derived
   (docs/decisions/0014-one-registry.md).

     teams/index.js  ->  TEAM_REGISTRY  ->  TeamOS.registry  ->  the chooser
                                                              ->  the boot script
                                                              ->  the worker

   Fields:

     id          the Suite's own id for the program. Lower case, digits and
                 hyphens only - it becomes a file name and a ?team= value, and
                 the boot script refuses anything else.
     name        how the program is written out.
     short       how it is written where space is tight.
     conference  for grouping in the chooser. A program with none says
                 "Independent".
     config      teams/<id>.js, when one exists. ABSENT means the program is
                 known but not yet selectable, which is a real state: it is
                 what the chooser greys out rather than hiding.

   GENERATED by tools/build-registry.js from ESPN's standings page, weekly,
   by the Action. Do not hand-edit the roster or the conferences: the next run
   overwrites them. `name` IS preserved across runs, for the case where the
   product calls a program something the provider does not.

   Making a program selectable is writing teams/<id>.js. The generator reads
   the filesystem and fills `config` in for you; nothing declares availability.

   The roster is a UNION across runs, so a bad parse can never remove a
   program, and the generator refuses to shrink it or to emit a list too short
   to be FBS. tools/registrycheck.js keeps it honest either way. */

var TEAM_REGISTRY = [

  { id: "air-force", name: "Air Force", short: "Air Force", conference: "Mountain West Conference", abbr: "AFA", nick: "Falcons" },
  { id: "akron", name: "Akron", short: "Akron", conference: "Mid-American Conference", abbr: "AKR", nick: "Zips" },
  { id: "alabama", name: "Alabama", short: "Alabama", conference: "Southeastern Conference", abbr: "ALA", nick: "Crimson Tide" },
  { id: "app-state", name: "App State", short: "App State", conference: "Sun Belt Conference", abbr: "APP", nick: "Mountaineers" },
  { id: "arizona", name: "Arizona", short: "Arizona", conference: "Big 12 Conference", abbr: "ARIZ", nick: "Wildcats" },
  { id: "arizona-state", name: "Arizona State", short: "Arizona State", conference: "Big 12 Conference", abbr: "ASU", nick: "Sun Devils" },
  { id: "arkansas", name: "Arkansas", short: "Arkansas", conference: "Southeastern Conference", abbr: "ARK", nick: "Razorbacks" },
  { id: "arkansas-state", name: "Arkansas State", short: "Arkansas State", conference: "Sun Belt Conference", abbr: "ARST", nick: "Red Wolves" },
  { id: "army", name: "Army", short: "Army", conference: "American Conference", abbr: "ARMY", nick: "Black Knights" },
  { id: "auburn", name: "Auburn", short: "Auburn", conference: "Southeastern Conference", abbr: "AUB", nick: "Tigers" },
  { id: "ball-state", name: "Ball State", short: "Ball State", conference: "Mid-American Conference", abbr: "BALL", nick: "Cardinals" },
  { id: "baylor", name: "Baylor", short: "Baylor", conference: "Big 12 Conference", abbr: "BAY", nick: "Bears" },
  { id: "boise-state", name: "Boise State", short: "Boise State", conference: "Pac-12 Conference", abbr: "BOIS", nick: "Broncos" },
  { id: "boston-college", name: "Boston College", short: "Boston College", conference: "Atlantic Coast Conference", abbr: "BC", nick: "Eagles" },
  { id: "bowling-green", name: "Bowling Green", short: "Bowling Green", conference: "Mid-American Conference", abbr: "BGSU", nick: "Falcons" },
  { id: "buffalo", name: "Buffalo", short: "Buffalo", conference: "Mid-American Conference", abbr: "BUFF", nick: "Bulls" },
  { id: "byu", name: "BYU", short: "BYU", conference: "Big 12 Conference", abbr: "BYU", nick: "Cougars" },
  { id: "california", name: "California", short: "California", conference: "Atlantic Coast Conference", abbr: "CAL", nick: "Golden Bears" },
  { id: "central-michigan", name: "Central Michigan", short: "Central Michigan", conference: "Mid-American Conference", abbr: "CMU", nick: "Chippewas" },
  { id: "charlotte", name: "Charlotte", short: "Charlotte", conference: "American Conference", abbr: "CLT", nick: "49ers" },
  { id: "cincinnati", name: "Cincinnati", short: "Cincinnati", conference: "Big 12 Conference", abbr: "CIN", nick: "Bearcats" },
  { id: "clemson", name: "Clemson", short: "Clemson", conference: "Atlantic Coast Conference", abbr: "CLEM", nick: "Tigers" },
  { id: "coastal-carolina", name: "Coastal Carolina", short: "Coastal Carolina", conference: "Sun Belt Conference", abbr: "CCU", nick: "Chanticleers" },
  { id: "colorado", name: "Colorado", short: "Colorado", conference: "Big 12 Conference", abbr: "COLO", nick: "Buffaloes" },
  { id: "colorado-state", name: "Colorado State", short: "Colorado State", conference: "Pac-12 Conference", abbr: "CSU", nick: "Rams" },
  { id: "delaware", name: "Delaware", short: "Delaware", conference: "Conference USA", abbr: "DEL", nick: "Blue Hens" },
  { id: "duke", name: "Duke", short: "Duke", conference: "Atlantic Coast Conference", abbr: "DUKE", nick: "Blue Devils" },
  { id: "east-carolina", name: "East Carolina", short: "East Carolina", conference: "American Conference", abbr: "ECU", nick: "Pirates" },
  { id: "eastern-michigan", name: "Eastern Michigan", short: "Eastern Michigan", conference: "Mid-American Conference", abbr: "EMU", nick: "Eagles" },
  { id: "florida", name: "Florida", short: "Florida", conference: "Southeastern Conference", abbr: "FLA", nick: "Gators" },
  { id: "florida-atlantic", name: "Florida Atlantic", short: "Florida Atlantic", conference: "American Conference", abbr: "FAU", nick: "Owls" },
  { id: "florida-international", name: "Florida International", short: "Florida International", conference: "Conference USA", abbr: "FIU", nick: "Panthers" },
  { id: "florida-state", name: "Florida State", short: "Florida State", conference: "Atlantic Coast Conference", abbr: "FSU", nick: "Seminoles" },
  { id: "fresno-state", name: "Fresno State", short: "Fresno State", conference: "Pac-12 Conference", abbr: "FRES", nick: "Bulldogs" },
  { id: "georgia", name: "Georgia", short: "Georgia", conference: "Southeastern Conference", abbr: "UGA", nick: "Bulldogs" },
  { id: "georgia-southern", name: "Georgia Southern", short: "Georgia Southern", conference: "Sun Belt Conference", abbr: "GASO", nick: "Eagles" },
  { id: "georgia-state", name: "Georgia State", short: "Georgia State", conference: "Sun Belt Conference", abbr: "GAST", nick: "Panthers" },
  { id: "georgia-tech", name: "Georgia Tech", short: "Georgia Tech", conference: "Atlantic Coast Conference", abbr: "GT", nick: "Yellow Jackets" },
  { id: "hawaii", name: "Hawai'i", short: "Hawai'i", conference: "Mountain West Conference", abbr: "HAW", nick: "Rainbow Warriors" },
  { id: "houston", name: "Houston", short: "Houston", conference: "Big 12 Conference", abbr: "HOU", nick: "Cougars" },
  { id: "illinois", name: "Illinois", short: "Illinois", conference: "Big Ten Conference", abbr: "ILL", nick: "Fighting Illini" },
  { id: "indiana", name: "Indiana", short: "Indiana", conference: "Big Ten Conference", abbr: "IU", nick: "Hoosiers" },
  { id: "iowa", name: "Iowa", short: "Iowa", conference: "Big Ten Conference", abbr: "IOWA", nick: "Hawkeyes" },
  { id: "iowa-state", name: "Iowa State", short: "Iowa State", conference: "Big 12 Conference", abbr: "ISU", nick: "Cyclones" },
  { id: "jacksonville-state", name: "Jacksonville State", short: "Jacksonville State", conference: "Conference USA", abbr: "JXST", nick: "Gamecocks" },
  { id: "james-madison", name: "James Madison", short: "James Madison", conference: "Sun Belt Conference", abbr: "JMU", nick: "Dukes" },
  { id: "kansas", name: "Kansas", short: "Kansas", conference: "Big 12 Conference", abbr: "KU", nick: "Jayhawks" },
  { id: "kansas-state", name: "Kansas State", short: "Kansas State", conference: "Big 12 Conference", abbr: "KSU", nick: "Wildcats" },
  { id: "kennesaw-state", name: "Kennesaw State", short: "Kennesaw State", conference: "Conference USA", abbr: "KENN", nick: "Owls" },
  { id: "kent-state", name: "Kent State", short: "Kent State", conference: "Mid-American Conference", abbr: "KENT", nick: "Golden Flashes" },
  { id: "kentucky", name: "Kentucky", short: "Kentucky", conference: "Southeastern Conference", abbr: "UK", nick: "Wildcats" },
  { id: "liberty", name: "Liberty", short: "Liberty", conference: "Conference USA", abbr: "LIB", nick: "Flames" },
  { id: "louisiana", name: "Louisiana", short: "Louisiana", conference: "Sun Belt Conference", abbr: "UL", nick: "Ragin' Cajuns" },
  { id: "louisiana-tech", name: "Louisiana Tech", short: "Louisiana Tech", conference: "Sun Belt Conference", abbr: "LT", nick: "Bulldogs" },
  { id: "louisville", name: "Louisville", short: "Louisville", conference: "Atlantic Coast Conference", abbr: "LOU", nick: "Cardinals" },
  { id: "lsu", name: "LSU", short: "LSU", conference: "Southeastern Conference", abbr: "LSU", nick: "Tigers" },
  { id: "marshall", name: "Marshall", short: "Marshall", conference: "Sun Belt Conference", abbr: "MRSH", nick: "Thundering Herd" },
  { id: "maryland", name: "Maryland", short: "Maryland", conference: "Big Ten Conference", abbr: "MD", nick: "Terrapins" },
  { id: "massachusetts", name: "Massachusetts", short: "Massachusetts", conference: "Mid-American Conference", abbr: "MASS", nick: "Minutemen" },
  { id: "memphis", name: "Memphis", short: "Memphis", conference: "American Conference", abbr: "MEM", nick: "Tigers" },
  { id: "miami", name: "Miami", short: "Miami", conference: "Atlantic Coast Conference", abbr: "MIA", nick: "Hurricanes" },
  { id: "miami-oh", name: "Miami (OH)", short: "Miami (OH)", conference: "Mid-American Conference", abbr: "M-OH", nick: "RedHawks" },
  { id: "michigan", name: "Michigan", short: "Michigan", conference: "Big Ten Conference", abbr: "MICH", nick: "Wolverines" },
  { id: "michigan-state", name: "Michigan State", short: "Michigan State", conference: "Big Ten Conference", abbr: "MSU", nick: "Spartans" },
  { id: "middle-tennessee", name: "Middle Tennessee", short: "Middle Tennessee", conference: "Conference USA", abbr: "MTSU", nick: "Blue Raiders" },
  { id: "minnesota", name: "Minnesota", short: "Minnesota", conference: "Big Ten Conference", abbr: "MINN", nick: "Golden Gophers" },
  { id: "mississippi-state", name: "Mississippi State", short: "Mississippi State", conference: "Southeastern Conference", abbr: "MSST", nick: "Bulldogs" },
  { id: "missouri", name: "Missouri", short: "Missouri", conference: "Southeastern Conference", abbr: "MIZ", nick: "Tigers" },
  { id: "missouri-state", name: "Missouri State", short: "Missouri State", conference: "Conference USA", abbr: "MOST", nick: "Bears" },
  { id: "navy", name: "Navy", short: "Navy", conference: "American Conference", abbr: "NAVY", nick: "Midshipmen" },
  { id: "nc-state", name: "NC State", short: "NC State", conference: "Atlantic Coast Conference", abbr: "NCSU", nick: "Wolfpack" },
  { id: "nebraska", name: "Nebraska", short: "Nebraska", conference: "Big Ten Conference", abbr: "NEB", nick: "Cornhuskers" },
  { id: "nevada", name: "Nevada", short: "Nevada", conference: "Mountain West Conference", abbr: "NEV", nick: "Wolf Pack" },
  { id: "new-mexico", name: "New Mexico", short: "New Mexico", conference: "Mountain West Conference", abbr: "UNM", nick: "Lobos" },
  { id: "new-mexico-state", name: "New Mexico State", short: "New Mexico State", conference: "Conference USA", abbr: "NMSU", nick: "Aggies" },
  { id: "north-carolina", name: "North Carolina", short: "North Carolina", conference: "Atlantic Coast Conference", abbr: "UNC", nick: "Tar Heels" },
  { id: "north-dakota-state", name: "North Dakota State", short: "North Dakota State", conference: "Mountain West Conference", abbr: "NDSU", nick: "Bison" },
  { id: "north-texas", name: "North Texas", short: "North Texas", conference: "American Conference", abbr: "UNT", nick: "Mean Green" },
  { id: "northern-illinois", name: "Northern Illinois", short: "Northern Illinois", conference: "Mountain West Conference", abbr: "NIU", nick: "Huskies" },
  { id: "northwestern", name: "Northwestern", short: "Northwestern", conference: "Big Ten Conference", abbr: "NU", nick: "Wildcats" },
  { id: "notre-dame", name: "Notre Dame", short: "Notre Dame", conference: "FBS Independents", abbr: "ND", nick: "Fighting Irish", config: "teams/notre-dame.js" },
  { id: "ohio", name: "Ohio", short: "Ohio", conference: "Mid-American Conference", abbr: "OHIO", nick: "Bobcats" },
  { id: "ohio-state", name: "Ohio State", short: "Ohio State", conference: "Big Ten Conference", abbr: "OSU", nick: "Buckeyes", config: "teams/ohio-state.js" },
  { id: "oklahoma", name: "Oklahoma", short: "Oklahoma", conference: "Southeastern Conference", abbr: "OU", nick: "Sooners" },
  { id: "oklahoma-state", name: "Oklahoma State", short: "Oklahoma State", conference: "Big 12 Conference", abbr: "OKST", nick: "Cowboys" },
  { id: "old-dominion", name: "Old Dominion", short: "Old Dominion", conference: "Sun Belt Conference", abbr: "ODU", nick: "Monarchs" },
  { id: "ole-miss", name: "Ole Miss", short: "Ole Miss", conference: "Southeastern Conference", abbr: "MISS", nick: "Rebels" },
  { id: "oregon", name: "Oregon", short: "Oregon", conference: "Big Ten Conference", abbr: "ORE", nick: "Ducks" },
  { id: "oregon-state", name: "Oregon State", short: "Oregon State", conference: "Pac-12 Conference", abbr: "ORST", nick: "Beavers" },
  { id: "penn-state", name: "Penn State", short: "Penn State", conference: "Big Ten Conference", abbr: "PSU", nick: "Nittany Lions" },
  { id: "pittsburgh", name: "Pittsburgh", short: "Pittsburgh", conference: "Atlantic Coast Conference", abbr: "PITT", nick: "Panthers" },
  { id: "purdue", name: "Purdue", short: "Purdue", conference: "Big Ten Conference", abbr: "PUR", nick: "Boilermakers" },
  { id: "rice", name: "Rice", short: "Rice", conference: "American Conference", abbr: "RICE", nick: "Owls" },
  { id: "rutgers", name: "Rutgers", short: "Rutgers", conference: "Big Ten Conference", abbr: "RUTG", nick: "Scarlet Knights" },
  { id: "sacramento-state", name: "Sacramento State", short: "Sacramento State", conference: "Mid-American Conference", abbr: "SAC", nick: "Hornets" },
  { id: "sam-houston", name: "Sam Houston", short: "Sam Houston", conference: "Conference USA", abbr: "SHSU", nick: "Bearkats" },
  { id: "san-diego-state", name: "San Diego State", short: "San Diego State", conference: "Pac-12 Conference", abbr: "SDSU", nick: "Aztecs" },
  { id: "san-jose-state", name: "San José State", short: "San José State", conference: "Mountain West Conference", abbr: "SJSU", nick: "Spartans" },
  { id: "smu", name: "SMU", short: "SMU", conference: "Atlantic Coast Conference", abbr: "SMU", nick: "Mustangs" },
  { id: "south-alabama", name: "South Alabama", short: "South Alabama", conference: "Sun Belt Conference", abbr: "USA", nick: "Jaguars" },
  { id: "south-carolina", name: "South Carolina", short: "South Carolina", conference: "Southeastern Conference", abbr: "SC", nick: "Gamecocks" },
  { id: "south-florida", name: "South Florida", short: "South Florida", conference: "American Conference", abbr: "USF", nick: "Bulls" },
  { id: "southern-miss", name: "Southern Miss", short: "Southern Miss", conference: "Sun Belt Conference", abbr: "USM", nick: "Golden Eagles" },
  { id: "stanford", name: "Stanford", short: "Stanford", conference: "Atlantic Coast Conference", abbr: "STAN", nick: "Cardinal" },
  { id: "syracuse", name: "Syracuse", short: "Syracuse", conference: "Atlantic Coast Conference", abbr: "SYR", nick: "Orange" },
  { id: "tcu", name: "TCU", short: "TCU", conference: "Big 12 Conference", abbr: "TCU", nick: "Horned Frogs" },
  { id: "temple", name: "Temple", short: "Temple", conference: "American Conference", abbr: "TEM", nick: "Owls" },
  { id: "tennessee", name: "Tennessee", short: "Tennessee", conference: "Southeastern Conference", abbr: "TENN", nick: "Volunteers" },
  { id: "texas", name: "Texas", short: "Texas", conference: "Southeastern Conference", abbr: "TEX", nick: "Longhorns" },
  { id: "texas-am", name: "Texas A&M", short: "Texas A&M", conference: "Southeastern Conference", abbr: "TA&M", nick: "Aggies" },
  { id: "texas-state", name: "Texas State", short: "Texas State", conference: "Pac-12 Conference", abbr: "TXST", nick: "Bobcats" },
  { id: "texas-tech", name: "Texas Tech", short: "Texas Tech", conference: "Big 12 Conference", abbr: "TTU", nick: "Red Raiders" },
  { id: "toledo", name: "Toledo", short: "Toledo", conference: "Mid-American Conference", abbr: "TOL", nick: "Rockets" },
  { id: "troy", name: "Troy", short: "Troy", conference: "Sun Belt Conference", abbr: "TROY", nick: "Trojans" },
  { id: "tulane", name: "Tulane", short: "Tulane", conference: "American Conference", abbr: "TULN", nick: "Green Wave" },
  { id: "tulsa", name: "Tulsa", short: "Tulsa", conference: "American Conference", abbr: "TLSA", nick: "Golden Hurricane" },
  { id: "uab", name: "UAB", short: "UAB", conference: "American Conference", abbr: "UAB", nick: "Blazers" },
  { id: "ucf", name: "UCF", short: "UCF", conference: "Big 12 Conference", abbr: "UCF", nick: "Knights" },
  { id: "ucla", name: "UCLA", short: "UCLA", conference: "Big Ten Conference", abbr: "UCLA", nick: "Bruins" },
  { id: "uconn", name: "UConn", short: "UConn", conference: "FBS Independents", abbr: "CONN", nick: "Huskies" },
  { id: "ul-monroe", name: "UL Monroe", short: "UL Monroe", conference: "Sun Belt Conference", abbr: "ULM", nick: "Warhawks" },
  { id: "unlv", name: "UNLV", short: "UNLV", conference: "Mountain West Conference", abbr: "UNLV", nick: "Rebels" },
  { id: "usc", name: "USC", short: "USC", conference: "Big Ten Conference", abbr: "USC", nick: "Trojans" },
  { id: "utah", name: "Utah", short: "Utah", conference: "Big 12 Conference", abbr: "UTAH", nick: "Utes" },
  { id: "utah-state", name: "Utah State", short: "Utah State", conference: "Pac-12 Conference", abbr: "USU", nick: "Aggies" },
  { id: "utep", name: "UTEP", short: "UTEP", conference: "Mountain West Conference", abbr: "UTEP", nick: "Miners" },
  { id: "utsa", name: "UTSA", short: "UTSA", conference: "American Conference", abbr: "UTSA", nick: "Roadrunners" },
  { id: "vanderbilt", name: "Vanderbilt", short: "Vanderbilt", conference: "Southeastern Conference", abbr: "VAN", nick: "Commodores" },
  { id: "virginia", name: "Virginia", short: "Virginia", conference: "Atlantic Coast Conference", abbr: "UVA", nick: "Cavaliers" },
  { id: "virginia-tech", name: "Virginia Tech", short: "Virginia Tech", conference: "Atlantic Coast Conference", abbr: "VT", nick: "Hokies" },
  { id: "wake-forest", name: "Wake Forest", short: "Wake Forest", conference: "Atlantic Coast Conference", abbr: "WAKE", nick: "Demon Deacons" },
  { id: "washington", name: "Washington", short: "Washington", conference: "Big Ten Conference", abbr: "WASH", nick: "Huskies" },
  { id: "washington-state", name: "Washington State", short: "Washington State", conference: "Pac-12 Conference", abbr: "WSU", nick: "Cougars" },
  { id: "west-virginia", name: "West Virginia", short: "West Virginia", conference: "Big 12 Conference", abbr: "WVU", nick: "Mountaineers" },
  { id: "western-kentucky", name: "Western Kentucky", short: "Western Kentucky", conference: "Conference USA", abbr: "WKU", nick: "Hilltoppers" },
  { id: "western-michigan", name: "Western Michigan", short: "Western Michigan", conference: "Mid-American Conference", abbr: "WMU", nick: "Broncos" },
  { id: "wisconsin", name: "Wisconsin", short: "Wisconsin", conference: "Big Ten Conference", abbr: "WIS", nick: "Badgers" },
  { id: "wyoming", name: "Wyoming", short: "Wyoming", conference: "Mountain West Conference", abbr: "WYO", nick: "Cowboys" }

];
