/* The canonical registry of programs this Suite knows about.

   One list, and only one. A program appears here whether or not the Suite can
   render it yet; what makes it selectable is that it names a `config`, and the
   config file existing is what makes that true. There is deliberately no
   second "available teams" list to drift out of step - availability is derived
   (docs/decisions/0014-one-registry.md).

     teams/index.js  ->  TEAM_REGISTRY  ->  TeamOS.registry  ->  the chooser
                                                              ->  the boot script
                                                              ->  the worker

   Fields:

     id          the Suite's own id for the program. Lower case, digits and
                 hyphens only - it becomes a file name and a ?team= value, and
                 the boot script refuses anything else.
     name        how the program is written out.
     short       how it is written where space is tight.
     conference  for grouping in the chooser. A program with none says
                 "Independent".
     config      teams/<id>.js, when one exists. ABSENT means the program is
                 known but not yet selectable, which is a real state: it is
                 what the chooser greys out rather than hiding.

   GENERATED by tools/build-registry.js from ESPN's standings page, weekly,
   by the Action. Do not hand-edit the roster or the conferences: the next run
   overwrites them. `name` IS preserved across runs, for the case where the
   product calls a program something the provider does not.

   Making a program selectable is writing teams/<id>.js. The generator reads
   the filesystem and fills `config` in for you; nothing declares availability.

   The roster is a UNION across runs, so a bad parse can never remove a
   program, and the generator refuses to shrink it or to emit a list too short
   to be FBS. tools/registrycheck.js keeps it honest either way. */

var TEAM_REGISTRY = [

  { id: "air-force", name: "Air Force", short: "Air Force", conference: "Mountain West Conference" },
  { id: "akron", name: "Akron", short: "Akron", conference: "Mid-American Conference" },
  { id: "alabama", name: "Alabama", short: "Alabama", conference: "Southeastern Conference" },
  { id: "app-state", name: "App State", short: "App State", conference: "Sun Belt Conference" },
  { id: "arizona", name: "Arizona", short: "Arizona", conference: "Big 12 Conference" },
  { id: "arizona-state", name: "Arizona State", short: "Arizona State", conference: "Big 12 Conference" },
  { id: "arkansas", name: "Arkansas", short: "Arkansas", conference: "Southeastern Conference" },
  { id: "arkansas-state", name: "Arkansas State", short: "Arkansas State", conference: "Sun Belt Conference" },
  { id: "army", name: "Army", short: "Army", conference: "American Conference" },
  { id: "auburn", name: "Auburn", short: "Auburn", conference: "Southeastern Conference" },
  { id: "ball-state", name: "Ball State", short: "Ball State", conference: "Mid-American Conference" },
  { id: "baylor", name: "Baylor", short: "Baylor", conference: "Big 12 Conference" },
  { id: "boise-state", name: "Boise State", short: "Boise State", conference: "Pac-12 Conference" },
  { id: "boston-college", name: "Boston College", short: "Boston College", conference: "Atlantic Coast Conference" },
  { id: "bowling-green", name: "Bowling Green", short: "Bowling Green", conference: "Mid-American Conference" },
  { id: "buffalo", name: "Buffalo", short: "Buffalo", conference: "Mid-American Conference" },
  { id: "byu", name: "BYU", short: "BYU", conference: "Big 12 Conference" },
  { id: "california", name: "California", short: "California", conference: "Atlantic Coast Conference" },
  { id: "central-michigan", name: "Central Michigan", short: "Central Michigan", conference: "Mid-American Conference" },
  { id: "charlotte", name: "Charlotte", short: "Charlotte", conference: "American Conference" },
  { id: "cincinnati", name: "Cincinnati", short: "Cincinnati", conference: "Big 12 Conference" },
  { id: "clemson", name: "Clemson", short: "Clemson", conference: "Atlantic Coast Conference" },
  { id: "coastal-carolina", name: "Coastal Carolina", short: "Coastal Carolina", conference: "Sun Belt Conference" },
  { id: "colorado", name: "Colorado", short: "Colorado", conference: "Big 12 Conference" },
  { id: "colorado-state", name: "Colorado State", short: "Colorado State", conference: "Pac-12 Conference" },
  { id: "delaware", name: "Delaware", short: "Delaware", conference: "Conference USA" },
  { id: "duke", name: "Duke", short: "Duke", conference: "Atlantic Coast Conference" },
  { id: "east-carolina", name: "East Carolina", short: "East Carolina", conference: "American Conference" },
  { id: "eastern-michigan", name: "Eastern Michigan", short: "Eastern Michigan", conference: "Mid-American Conference" },
  { id: "florida", name: "Florida", short: "Florida", conference: "Southeastern Conference" },
  { id: "florida-atlantic", name: "Florida Atlantic", short: "Florida Atlantic", conference: "American Conference" },
  { id: "florida-international", name: "Florida International", short: "Florida International", conference: "Conference USA" },
  { id: "florida-state", name: "Florida State", short: "Florida State", conference: "Atlantic Coast Conference" },
  { id: "fresno-state", name: "Fresno State", short: "Fresno State", conference: "Pac-12 Conference" },
  { id: "georgia", name: "Georgia", short: "Georgia", conference: "Southeastern Conference" },
  { id: "georgia-southern", name: "Georgia Southern", short: "Georgia Southern", conference: "Sun Belt Conference" },
  { id: "georgia-state", name: "Georgia State", short: "Georgia State", conference: "Sun Belt Conference" },
  { id: "georgia-tech", name: "Georgia Tech", short: "Georgia Tech", conference: "Atlantic Coast Conference" },
  { id: "hawaii", name: "Hawai'i", short: "Hawai'i", conference: "Mountain West Conference" },
  { id: "houston", name: "Houston", short: "Houston", conference: "Big 12 Conference" },
  { id: "illinois", name: "Illinois", short: "Illinois", conference: "Big Ten Conference" },
  { id: "indiana", name: "Indiana", short: "Indiana", conference: "Big Ten Conference" },
  { id: "iowa", name: "Iowa", short: "Iowa", conference: "Big Ten Conference" },
  { id: "iowa-state", name: "Iowa State", short: "Iowa State", conference: "Big 12 Conference" },
  { id: "jacksonville-state", name: "Jacksonville State", short: "Jacksonville State", conference: "Conference USA" },
  { id: "james-madison", name: "James Madison", short: "James Madison", conference: "Sun Belt Conference" },
  { id: "kansas", name: "Kansas", short: "Kansas", conference: "Big 12 Conference" },
  { id: "kansas-state", name: "Kansas State", short: "Kansas State", conference: "Big 12 Conference" },
  { id: "kennesaw-state", name: "Kennesaw State", short: "Kennesaw State", conference: "Conference USA" },
  { id: "kent-state", name: "Kent State", short: "Kent State", conference: "Mid-American Conference" },
  { id: "kentucky", name: "Kentucky", short: "Kentucky", conference: "Southeastern Conference" },
  { id: "liberty", name: "Liberty", short: "Liberty", conference: "Conference USA" },
  { id: "louisiana", name: "Louisiana", short: "Louisiana", conference: "Sun Belt Conference" },
  { id: "louisiana-tech", name: "Louisiana Tech", short: "Louisiana Tech", conference: "Sun Belt Conference" },
  { id: "louisville", name: "Louisville", short: "Louisville", conference: "Atlantic Coast Conference" },
  { id: "lsu", name: "LSU", short: "LSU", conference: "Southeastern Conference" },
  { id: "marshall", name: "Marshall", short: "Marshall", conference: "Sun Belt Conference" },
  { id: "maryland", name: "Maryland", short: "Maryland", conference: "Big Ten Conference" },
  { id: "massachusetts", name: "Massachusetts", short: "Massachusetts", conference: "Mid-American Conference" },
  { id: "memphis", name: "Memphis", short: "Memphis", conference: "American Conference" },
  { id: "miami", name: "Miami", short: "Miami", conference: "Atlantic Coast Conference" },
  { id: "miami-oh", name: "Miami (OH)", short: "Miami (OH)", conference: "Mid-American Conference" },
  { id: "michigan", name: "Michigan", short: "Michigan", conference: "Big Ten Conference" },
  { id: "michigan-state", name: "Michigan State", short: "Michigan State", conference: "Big Ten Conference" },
  { id: "middle-tennessee", name: "Middle Tennessee", short: "Middle Tennessee", conference: "Conference USA" },
  { id: "minnesota", name: "Minnesota", short: "Minnesota", conference: "Big Ten Conference" },
  { id: "mississippi-state", name: "Mississippi State", short: "Mississippi State", conference: "Southeastern Conference" },
  { id: "missouri", name: "Missouri", short: "Missouri", conference: "Southeastern Conference" },
  { id: "missouri-state", name: "Missouri State", short: "Missouri State", conference: "Conference USA" },
  { id: "navy", name: "Navy", short: "Navy", conference: "American Conference" },
  { id: "nc-state", name: "NC State", short: "NC State", conference: "Atlantic Coast Conference" },
  { id: "nebraska", name: "Nebraska", short: "Nebraska", conference: "Big Ten Conference" },
  { id: "nevada", name: "Nevada", short: "Nevada", conference: "Mountain West Conference" },
  { id: "new-mexico", name: "New Mexico", short: "New Mexico", conference: "Mountain West Conference" },
  { id: "new-mexico-state", name: "New Mexico State", short: "New Mexico State", conference: "Conference USA" },
  { id: "north-carolina", name: "North Carolina", short: "North Carolina", conference: "Atlantic Coast Conference" },
  { id: "north-dakota-state", name: "North Dakota State", short: "North Dakota State", conference: "Mountain West Conference" },
  { id: "north-texas", name: "North Texas", short: "North Texas", conference: "American Conference" },
  { id: "northern-illinois", name: "Northern Illinois", short: "Northern Illinois", conference: "Mountain West Conference" },
  { id: "northwestern", name: "Northwestern", short: "Northwestern", conference: "Big Ten Conference" },
  { id: "notre-dame", name: "Notre Dame", short: "Notre Dame", conference: "FBS Independents", config: "teams/notre-dame.js" },
  { id: "ohio", name: "Ohio", short: "Ohio", conference: "Mid-American Conference" },
  { id: "ohio-state", name: "Ohio State", short: "Ohio State", conference: "Big Ten Conference", config: "teams/ohio-state.js" },
  { id: "oklahoma", name: "Oklahoma", short: "Oklahoma", conference: "Southeastern Conference" },
  { id: "oklahoma-state", name: "Oklahoma State", short: "Oklahoma State", conference: "Big 12 Conference" },
  { id: "old-dominion", name: "Old Dominion", short: "Old Dominion", conference: "Sun Belt Conference" },
  { id: "ole-miss", name: "Ole Miss", short: "Ole Miss", conference: "Southeastern Conference" },
  { id: "oregon", name: "Oregon", short: "Oregon", conference: "Big Ten Conference" },
  { id: "oregon-state", name: "Oregon State", short: "Oregon State", conference: "Pac-12 Conference" },
  { id: "penn-state", name: "Penn State", short: "Penn State", conference: "Big Ten Conference" },
  { id: "pittsburgh", name: "Pittsburgh", short: "Pittsburgh", conference: "Atlantic Coast Conference" },
  { id: "purdue", name: "Purdue", short: "Purdue", conference: "Big Ten Conference" },
  { id: "rice", name: "Rice", short: "Rice", conference: "American Conference" },
  { id: "rutgers", name: "Rutgers", short: "Rutgers", conference: "Big Ten Conference" },
  { id: "sacramento-state", name: "Sacramento State", short: "Sacramento State", conference: "Mid-American Conference" },
  { id: "sam-houston", name: "Sam Houston", short: "Sam Houston", conference: "Conference USA" },
  { id: "san-diego-state", name: "San Diego State", short: "San Diego State", conference: "Pac-12 Conference" },
  { id: "san-jos-state", name: "San José State", short: "San José State", conference: "Mountain West Conference" },
  { id: "smu", name: "SMU", short: "SMU", conference: "Atlantic Coast Conference" },
  { id: "south-alabama", name: "South Alabama", short: "South Alabama", conference: "Sun Belt Conference" },
  { id: "south-carolina", name: "South Carolina", short: "South Carolina", conference: "Southeastern Conference" },
  { id: "south-florida", name: "South Florida", short: "South Florida", conference: "American Conference" },
  { id: "southern-miss", name: "Southern Miss", short: "Southern Miss", conference: "Sun Belt Conference" },
  { id: "stanford", name: "Stanford", short: "Stanford", conference: "Atlantic Coast Conference" },
  { id: "syracuse", name: "Syracuse", short: "Syracuse", conference: "Atlantic Coast Conference" },
  { id: "tcu", name: "TCU", short: "TCU", conference: "Big 12 Conference" },
  { id: "temple", name: "Temple", short: "Temple", conference: "American Conference" },
  { id: "tennessee", name: "Tennessee", short: "Tennessee", conference: "Southeastern Conference" },
  { id: "texas", name: "Texas", short: "Texas", conference: "Southeastern Conference" },
  { id: "texas-aandm", name: "Texas A&M", short: "Texas A&M", conference: "Southeastern Conference" },
  { id: "texas-state", name: "Texas State", short: "Texas State", conference: "Pac-12 Conference" },
  { id: "texas-tech", name: "Texas Tech", short: "Texas Tech", conference: "Big 12 Conference" },
  { id: "toledo", name: "Toledo", short: "Toledo", conference: "Mid-American Conference" },
  { id: "troy", name: "Troy", short: "Troy", conference: "Sun Belt Conference" },
  { id: "tulane", name: "Tulane", short: "Tulane", conference: "American Conference" },
  { id: "tulsa", name: "Tulsa", short: "Tulsa", conference: "American Conference" },
  { id: "uab", name: "UAB", short: "UAB", conference: "American Conference" },
  { id: "ucf", name: "UCF", short: "UCF", conference: "Big 12 Conference" },
  { id: "ucla", name: "UCLA", short: "UCLA", conference: "Big Ten Conference" },
  { id: "uconn", name: "UConn", short: "UConn", conference: "FBS Independents" },
  { id: "ul-monroe", name: "UL Monroe", short: "UL Monroe", conference: "Sun Belt Conference" },
  { id: "unlv", name: "UNLV", short: "UNLV", conference: "Mountain West Conference" },
  { id: "usc", name: "USC", short: "USC", conference: "Big Ten Conference" },
  { id: "utah", name: "Utah", short: "Utah", conference: "Big 12 Conference" },
  { id: "utah-state", name: "Utah State", short: "Utah State", conference: "Pac-12 Conference" },
  { id: "utep", name: "UTEP", short: "UTEP", conference: "Mountain West Conference" },
  { id: "utsa", name: "UTSA", short: "UTSA", conference: "American Conference" },
  { id: "vanderbilt", name: "Vanderbilt", short: "Vanderbilt", conference: "Southeastern Conference" },
  { id: "virginia", name: "Virginia", short: "Virginia", conference: "Atlantic Coast Conference" },
  { id: "virginia-tech", name: "Virginia Tech", short: "Virginia Tech", conference: "Atlantic Coast Conference" },
  { id: "wake-forest", name: "Wake Forest", short: "Wake Forest", conference: "Atlantic Coast Conference" },
  { id: "washington", name: "Washington", short: "Washington", conference: "Big Ten Conference" },
  { id: "washington-state", name: "Washington State", short: "Washington State", conference: "Pac-12 Conference" },
  { id: "west-virginia", name: "West Virginia", short: "West Virginia", conference: "Big 12 Conference" },
  { id: "western-kentucky", name: "Western Kentucky", short: "Western Kentucky", conference: "Conference USA" },
  { id: "western-michigan", name: "Western Michigan", short: "Western Michigan", conference: "Mid-American Conference" },
  { id: "wisconsin", name: "Wisconsin", short: "Wisconsin", conference: "Big Ten Conference" },
  { id: "wyoming", name: "Wyoming", short: "Wyoming", conference: "Mountain West Conference" }

];
